name: PR Version Validation (Prod, Master)
on:
  pull_request: {}

jobs:
  validate:
    uses: mkaraki/mkarakiapps-releasing-actions/.github/workflows/pr-version-validator.yaml@0a6afbadbdbaca99dcc27f20b9e06aa8c4f25ce5
    with:
      target-branch: ${{ github.base_ref }}
      version-file: version.go
      version-file-format: php
