name: PR Version Validation (Prod, Master)
on:
  pull_request: {}

jobs:
  validate:
    uses: mkaraki/mkarakiapps-releasing-actions/.github/workflows/pr-version-validator.yaml@15662b3c362acb3a1fd5fa453e12c9ca5fe2a2ce
    with:
      target-branch: ${{ github.base_ref }}
      version-file: version.go
      version-file-format: php
